package verwaltung;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Limbo
 * Belege zu Kunde zweigt alle Belge eines Kunden an
 */
public class Belege_Kunde extends javax.swing.JFrame {

    //Klassenweite variablen
    String [][] alle;
    String name, kdnr, Vorname, Nachname;
    int recht;
    
    //Konstruktor
    public Belege_Kunde(String [][] alle,int recht, String name, String kdnr, String Vorname, String Nachname) {
        Image icon = new ImageIcon("ic_lagerverwaltung32.gif").getImage();
        setIconImage(icon);
        initComponents();
        this.alle=alle;
        this.recht = recht;
        this.name=name;
        this.kdnr=kdnr;
        this.Vorname=Vorname;
        this.Nachname=Nachname;
        jlueberschrift.setText("Belege von: "+Nachname+", "+Vorname);
        Tabelle_fuellen();
    }
    
       public Belege_Kunde() {
        initComponents();
    }
    
    public void Tabelle_fuellen()
    {   
        //Tabelle füllen
        Object[] row = new Object[4];
        DefaultTableModel model = (DefaultTableModel) jtbelege.getModel();
        model.setRowCount(0);
        
        for (int i=0; i< alle.length; i++)
        {
            row[0]= alle[i][0];
            row[1]= alle[i][1];
            row[2]= alle[i][2];
            row[3]= alle[i][3];
 
            model.addRow(row);
        }
        
        //Anzahl der Zeilen anzeigen
        jlrow.setText(alle.length + " Rows returned");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlueberschrift = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbelege = new javax.swing.JTable();
        jlrow = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Belege eines Kunden");

        jlueberschrift.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlueberschrift.setText("Belege eines Kunden");

        jtbelege.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bestell_ID", "Zeit", "Status", "SummeArtikel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbelege.getTableHeader().setReorderingAllowed(false);
        jtbelege.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbelegeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtbelegeMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jtbelege);

        jlrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table.gif"))); // NOI18N
        jlrow.setText("Zeilenanzahl");

        jMenu1.setText("Belege");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.gif"))); // NOI18N
        jMenuItem1.setText("beenden");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlueberschrift)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlrow))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlueberschrift)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlrow)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //jmbeenden
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jtbelegeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbelegeMouseClicked
        // Bei Doppelklick auf eine Spalte
        if (evt.getClickCount()==2) 
		{ 
                    Bestellung B = new Bestellung(recht, name, alle[jtbelege.getSelectedRow()][0],kdnr, Vorname, Nachname, alle[jtbelege.getSelectedRow()][2]);
                     B.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
                     B.setVisible(true);
		}
    }//GEN-LAST:event_jtbelegeMouseClicked

    private void jtbelegeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbelegeMouseEntered
        // Wenn die Maus auf die Tabelle fährt
        jtbelege.setToolTipText("Doppelklick öffnet den Beleg!");
        
    }//GEN-LAST:event_jtbelegeMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Belege_Kunde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Belege_Kunde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Belege_Kunde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Belege_Kunde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Belege_Kunde().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlrow;
    private javax.swing.JLabel jlueberschrift;
    private javax.swing.JTable jtbelege;
    // End of variables declaration//GEN-END:variables
}
