/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package verwaltung;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import testcommon.TestService;

/**
 * @author Limbo
 * Fenster zur Benutzerverwaltung
 */
public class Benutzerverwaltung extends javax.swing.JFrame {

    //Klassenweite variablen
   TestService myServiceCaller;
    Einstellungen E;
    String[][] alle;
    int akt =0;

    //Konstruktor
    public Benutzerverwaltung() {
        //Fenster aufbau
        initComponents();
        //vorerst nicht benötigte Elemente ausblenden
        jlpass.setVisible(false);
        jtpass1.setVisible(false);
        jtpass2.setVisible(false);
        jlpassneu.setVisible(false);
        Image icon = new ImageIcon("ic_lagerverwaltung32.gif").getImage();
        setIconImage(icon);
        //Connection aufbau
        E = new Einstellungen();
        this.myServiceCaller = E.connection();
        //Alle Benutzer holen
        alle = myServiceCaller.AlleBenutzer();
        //Tabelle mit Benutzern füllen
        Tabelle_fuellen();
    }
    
    //Tabelle füllen
     public void Tabelle_fuellen()
    {   

        Object[] row = new Object[4];
        DefaultTableModel model = (DefaultTableModel) jtuser.getModel();
        model.setRowCount(0);
        
        for (int i=0; i< alle.length; i++)
        {
            row[0]= alle[i][0];
            row[1]= alle[i][1];
            row[2]= alle[i][2];
            row[3]= alle[i][3];

            model.addRow(row);
        }
        
        //Anzahl der Zeilen anzeigen
        jlrow.setText(alle.length + " Rows returned");
        jcheckpass.setSelected(false);
        jlpassneu.setText("Passwort erneut eingeben:");
        jlpassneu.setForeground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtuser = new javax.swing.JTable();
        jlrow = new javax.swing.JLabel();
        jbsave = new javax.swing.JButton();
        jbdelete = new javax.swing.JButton();
        jbnew = new javax.swing.JButton();
        jppasswort = new javax.swing.JPanel();
        jlpass = new javax.swing.JLabel();
        jtpass1 = new javax.swing.JPasswordField();
        jlpassneu = new javax.swing.JLabel();
        jtpass2 = new javax.swing.JPasswordField();
        jcheckpass = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jluser = new javax.swing.JLabel();
        jtuserid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtname = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jcrecht = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Benutzerverwaltung");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Benutzer");

        jtuser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User_ID", "Name", "Passwort", "Berechtigung"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtuserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtuser);
        if (jtuser.getColumnModel().getColumnCount() > 0) {
            jtuser.getColumnModel().getColumn(0).setPreferredWidth(30);
            jtuser.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        jlrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table.gif"))); // NOI18N
        jlrow.setText("Rows");

        jbsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.gif"))); // NOI18N
        jbsave.setText("änderung speichern");
        jbsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsaveActionPerformed(evt);
            }
        });

        jbdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.gif"))); // NOI18N
        jbdelete.setText("Benutzer löschen");
        jbdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdeleteActionPerformed(evt);
            }
        });

        jbnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.gif"))); // NOI18N
        jbnew.setText("Neuer Benutzer");
        jbnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnewActionPerformed(evt);
            }
        });

        jppasswort.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlpass.setText("Passwort:");

        jlpassneu.setText("Passwort erneut eingeben:");

        jtpass2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtpass2KeyReleased(evt);
            }
        });

        jcheckpass.setText("Passwort ändern");
        jcheckpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcheckpassMouseClicked(evt);
            }
        });
        jcheckpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jppasswortLayout = new javax.swing.GroupLayout(jppasswort);
        jppasswort.setLayout(jppasswortLayout);
        jppasswortLayout.setHorizontalGroup(
            jppasswortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jppasswortLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jppasswortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jppasswortLayout.createSequentialGroup()
                        .addGroup(jppasswortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtpass2)
                            .addComponent(jtpass1))
                        .addContainerGap())
                    .addGroup(jppasswortLayout.createSequentialGroup()
                        .addGroup(jppasswortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlpass)
                            .addComponent(jlpassneu, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcheckpass))
                        .addGap(34, 34, 34))))
        );
        jppasswortLayout.setVerticalGroup(
            jppasswortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jppasswortLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcheckpass)
                .addGap(12, 12, 12)
                .addComponent(jlpass)
                .addGap(18, 18, 18)
                .addComponent(jtpass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jlpassneu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtpass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jluser.setText("User_ID:");

        jLabel5.setText("Benutzername:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtname)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jluser)
                                .addGap(18, 18, 18)
                                .addComponent(jtuserid, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGap(45, 45, 45)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jluser)
                    .addComponent(jtuserid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jLabel6.setText("Recht:");

        jcrecht.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1 Admnistrator", "2 Anwender", "3 Praktikant" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jcrecht, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcrecht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Benutzerverwaltung");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jlrow, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jppasswort, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbnew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbsave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbdelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbnew)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jppasswort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbsave)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlrow)
                    .addComponent(jbdelete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtuserMouseClicked
        // Klicken auf die Tabelle
        akt = jtuser.getSelectedRow();
        //Table modell holen und aus den Spalten holen und in die Textfelder / JComboboxen füllen
        TableModel model = jtuser.getModel();
        //Textfelder / Combofelder bestücken
        jtuserid.setText((String) model.getValueAt(akt, 0));
        jtname.setText((String) model.getValueAt(akt, 1));
        jcrecht.setSelectedIndex(Integer.parseInt(alle[akt][3]));
        jcheckpass.setVisible(true);
        jlpass.setVisible(false);
        jtpass1.setVisible(false);
        jtpass2.setVisible(false);
        jlpassneu.setVisible(false);
        jtname.setVisible(true);
        jluser.setVisible(true);
        jtuserid.setVisible(true);
        
    }//GEN-LAST:event_jtuserMouseClicked

    private void jbnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnewActionPerformed
        // Neuer Benutzer anlegen
        //erstmal Elemente einblenden
        jluser.setVisible(false);
        jtuserid.setVisible(false);
        jtpass1.setText("");
        jtpass2.setText("");
        jtname.setText("");
        jcrecht.setSelectedIndex(0);
        jlpass.setVisible(true);
        jtpass1.setVisible(true);
        jtpass2.setVisible(true);
        jlpassneu.setVisible(true);
        jbsave.setText("speichern");
        jcheckpass.setVisible(false);
        jtuserid.setText("");

    }//GEN-LAST:event_jbnewActionPerformed

    private void jbsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsaveActionPerformed
        // Speichern Button
        //String passwort = E.build_md5(new String(zeichen));
        int err=0;
        String pass1="", pass2="", result="";
        char[] zeichen;
        if (jtuserid.getText().equals(""))
        {
            int ok = JOptionPane.showConfirmDialog(null, "Benutzer anlegen ?", "neuer Benutzer" , JOptionPane.YES_NO_OPTION);
            //ok==0 == ja
            if (ok == 0)
            {
                //Prüfen der eingaben
                if (jtname.getText().equals(""))
                {
                     JOptionPane.showMessageDialog(null, "Kein Benutzer vorhanden!", "Fehler", JOptionPane.ERROR_MESSAGE);
                     err = err + 1;
                }
                
                //Gleiche eingabe von Passwörtern prüfen
                zeichen = jtpass1.getPassword();
                pass1 = new String(zeichen);
                
                //Auf die länge Prüfen
                if (zeichen.length < 5)
                {
                    JOptionPane.showMessageDialog(null, "Das eingegebene Passwort ist zu kurz!", "Fehler", JOptionPane.ERROR_MESSAGE);
                     err = err + 1;
                }
                
                zeichen = jtpass2.getPassword();
                pass2 = new String(zeichen);
                
                //beide Felder mit einander vergleichen
                
                if (pass1.equals(pass2))
                {
                    System.out.println("Passwörter sind gleich");
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Die Passwörter sind Unterschiedlich!", "Fehler", JOptionPane.ERROR_MESSAGE);
                     err = err + 1;
                }
                
                if (jcrecht.getSelectedIndex()==0)
                {
                     JOptionPane.showMessageDialog(null, "Es wurde kein Recht ausgewählt!", "Fehler", JOptionPane.ERROR_MESSAGE);
                     err = err + 1;

                }
                
                if (err==0)
                {
                    //Benutzer einfügen und den Result auswärten
                    result = myServiceCaller.insertBenutzer(jtname.getText(), E.build_md5(pass2), Integer.toString(jcrecht.getSelectedIndex()));
                    //Meldung ausgeben
                    JOptionPane.showMessageDialog(null, result, "Erfolgreich", JOptionPane.INFORMATION_MESSAGE);
                    //Tabelle neue laden um auch den Benutzer anzuzeigen
                    alle = myServiceCaller.AlleBenutzer();
                    Tabelle_fuellen();
                    //neuesten Benutzer anzeigen
                     //Textfelder / JComboboxen füllen
                    akt=alle.length-1;
                    jluser.setVisible(true);
                    jtuserid.setVisible(true);
                    jtuserid.setText(alle[akt][0]);
                    jtname.setText(alle[akt][1]);
                    jcrecht.setSelectedIndex(Integer.parseInt(alle[akt][3]));
                    jbsave.setText("änderung speichern");
                }
            }
        }
        else
        { 
            //Prüfen der eingaben
                if (jtname.getText().equals(""))
                {
                     JOptionPane.showMessageDialog(null, "Kein Benutzer vorhanden!", "Fehler", JOptionPane.ERROR_MESSAGE);
                     err = err + 1;
                }
                
                if (jcheckpass.isSelected())
                {
                    //Gleiche eingabe von Passwörtern prüfen
                    zeichen = jtpass1.getPassword();
                    pass1 = new String(zeichen);

                    //Auf die länge Prüfen
                    if (zeichen.length < 5)
                    {
                        JOptionPane.showMessageDialog(null, "Das eingegebene Passwort ist zu kurz!", "Fehler", JOptionPane.ERROR_MESSAGE);
                         err = err + 1;
                    }

                    zeichen = jtpass2.getPassword();
                    pass2 = new String(zeichen);

                    //beide Felder mit einander vergleichen

                    if (pass1.equals(pass2))
                    {
                        System.out.println("Passwörter sind gleich");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Die Passwörter sind Unterschiedlich!", "Fehler", JOptionPane.ERROR_MESSAGE);
                         err = err + 1;
                    }
                }

                if (jcrecht.getSelectedIndex()==0)
                {
                     JOptionPane.showMessageDialog(null, "Es wurde kein Recht ausgewählt!", "Fehler", JOptionPane.ERROR_MESSAGE);
                     err = err + 1;
                }
                
                if (err==0)
                {
                    //wenn die passwörter box angehagt wurde dann soll auch das neue Passwort eingetragen werden
                    if (jcheckpass.isSelected())
                    {
                       result = myServiceCaller.updateBenutzer(alle[akt][0], jtname.getText(), E.build_md5(pass2), Integer.toString(jcrecht.getSelectedIndex())); 
                    }
                    else
                    {
                        result = myServiceCaller.updateBenutzer(alle[akt][0], jtname.getText(), alle[akt][2], Integer.toString(jcrecht.getSelectedIndex()));
                    }

                    //Meldung ausgeben
                    JOptionPane.showMessageDialog(null, result, "Erfolgreich", JOptionPane.INFORMATION_MESSAGE);
                    //Tabelle neue laden um auch den Benutzer anzuzeigen
                    alle = myServiceCaller.AlleBenutzer();
                    Tabelle_fuellen();
                    //Benutzer anzeigen
                     //Textfelder / JComboboxen füllen
                    akt=alle.length-1;
                    jluser.setVisible(true);
                    jtuserid.setVisible(true);
                    jtuserid.setText(alle[akt][0]);
                    jtname.setText(alle[akt][1]);
                    jcrecht.setSelectedIndex(Integer.parseInt(alle[akt][3]));
                    jbsave.setText("änderung speichern");
                }
        }
        
    }//GEN-LAST:event_jbsaveActionPerformed

    private void jcheckpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckpassActionPerformed
  
    }//GEN-LAST:event_jcheckpassActionPerformed

    private void jcheckpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcheckpassMouseClicked
        // wenn ausgewählt wurde das Passwort zu ändern:
        if (jcheckpass.isSelected())
        {
        jlpass.setVisible(true);
        jtpass1.setVisible(true);
        jtpass2.setVisible(true);
        jlpassneu.setVisible(true);
        }
        else
        {
         jlpass.setVisible(false);
        jtpass1.setVisible(false);
        jtpass2.setVisible(false);
        jlpassneu.setVisible(false);
        }   
    }//GEN-LAST:event_jcheckpassMouseClicked

    private void jbdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdeleteActionPerformed
        // Löschen Button
        //Message erstellen
        String result = "Möchten Sie den Benutzer "+jtuserid.getText()+", "+jtname.getText()+" wirklich löschen?";
        //Benutzer fragen
        int ok = JOptionPane.showConfirmDialog(null, result, "Löschen" , JOptionPane.YES_NO_OPTION);
            //ok==0 == ja
            if (ok == 0)
            {
                //Methode am Server aufrufen
               result=myServiceCaller.loescheBenutzer(jtuserid.getText());
               if (result.equals("Datensatz wurde gelöscht!"))
               {
                   //Meldung vom Server ausgeben
                    JOptionPane.showMessageDialog(null, result, "Erfolgreich", JOptionPane.INFORMATION_MESSAGE);
               }
               else
               {
                   //Meldung vom Server ausgeben
                    JOptionPane.showMessageDialog(null, result, "Fehler", JOptionPane.ERROR_MESSAGE);
               }  
               //Benutzer neu laden und anzeigen
               alle = myServiceCaller.AlleBenutzer();
               Tabelle_fuellen();
               //die Benutzerauswahl ist danach nicht ausgewählt
               jtuserid.setText("");
               jtname.setText("");
               jcrecht.setSelectedIndex(0);
               
               
            }
    }//GEN-LAST:event_jbdeleteActionPerformed

    private void jtpass2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpass2KeyReleased
        // wenn das zweite mal das Kennwort eingibt soll es gleich mit dem ersten Verglichen werden
        char [] passwort1;
        char [] passwort2;
        boolean ok=false;
        //Felder auslesen (bei jedem tastendruck)
        passwort1 = jtpass1.getPassword();
        passwort2 = jtpass2.getPassword();
        
        try
        { 
            //in der schleife jede stelle durchgehen
        for (int i = 0; i < passwort2.length; i++)
        {
            //prüfen ob jede stelle gleich ist
            if (passwort1[i] == passwort2[i])
            {
                //prüfen ob es gleich lang ist
                if (passwort1.length == passwort2.length)
                {
                    ok=true;
                }
            }
        }
        }
        catch(Exception ex) //wenn die zweite eingabe länger ist die erste (Array outofBound Exception) ok wird zu false - speichern wird unmöglich
        {
            ok=false;
        }
        //bei true -> ausgabe grün
        if (ok)
        {
            jlpassneu.setText("übereinstimmung");
            jlpassneu.setForeground(Color.GREEN);
        }
        else
        {
            jlpassneu.setText("keine übereinstimmung");
            jlpassneu.setForeground(Color.RED); 
        } 
    }//GEN-LAST:event_jtpass2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Benutzerverwaltung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Benutzerverwaltung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Benutzerverwaltung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Benutzerverwaltung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Benutzerverwaltung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbdelete;
    private javax.swing.JButton jbnew;
    private javax.swing.JButton jbsave;
    private javax.swing.JCheckBox jcheckpass;
    private javax.swing.JComboBox<String> jcrecht;
    private javax.swing.JLabel jlpass;
    private javax.swing.JLabel jlpassneu;
    private javax.swing.JLabel jlrow;
    private javax.swing.JLabel jluser;
    private javax.swing.JPanel jppasswort;
    private javax.swing.JTextField jtname;
    private javax.swing.JPasswordField jtpass1;
    private javax.swing.JPasswordField jtpass2;
    private javax.swing.JTable jtuser;
    private javax.swing.JTextField jtuserid;
    // End of variables declaration//GEN-END:variables
}
