/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package verwaltung;

import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import lipermi.handler.CallHandler;
import lipermi.handler.filter.GZipFilter;
import lipermi.net.Client;
import testcommon.TestService;

/**
 *
 * @author Limbo
 * Erstes Fenster beim start des Programms
 */
public class Login extends javax.swing.JFrame {

    //Konstruktor
    public Login() 
    {
        Image icon = new ImageIcon("ic_lagerverwaltung32.gif").getImage();
        setIconImage(icon);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtname = new javax.swing.JTextField();
        jtpasswd = new javax.swing.JPasswordField();
        jblogin = new javax.swing.JButton();
        jbclear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jbprogramm = new javax.swing.JMenu();
        jmlogin = new javax.swing.JMenuItem();
        jmbeenden = new javax.swing.JMenuItem();
        jmoptionen = new javax.swing.JMenu();
        jmeinstellungen = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocation(new java.awt.Point(200, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Verwaltung - Login");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Benutzername:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Passwort:");

        jblogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login.gif"))); // NOI18N
        jblogin.setText("Login");
        jblogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbloginActionPerformed(evt);
            }
        });

        jbclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clear.gif"))); // NOI18N
        jbclear.setText("Clear");
        jbclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbclearActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_lagerverwaltung144.gif"))); // NOI18N

        jbprogramm.setText("Programm");

        jmlogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
        jmlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login.gif"))); // NOI18N
        jmlogin.setText("Login");
        jmlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmloginActionPerformed(evt);
            }
        });
        jbprogramm.add(jmlogin);

        jmbeenden.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jmbeenden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ausschalten.gif"))); // NOI18N
        jmbeenden.setText("Beenden");
        jmbeenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbeendenActionPerformed(evt);
            }
        });
        jbprogramm.add(jmbeenden);

        jMenuBar1.add(jbprogramm);

        jmoptionen.setText("Optionen");

        jmeinstellungen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmeinstellungen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/settings.gif"))); // NOI18N
        jmeinstellungen.setText("Einstellungen");
        jmeinstellungen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmeinstellungenActionPerformed(evt);
            }
        });
        jmoptionen.add(jmeinstellungen);

        jMenuBar1.add(jmoptionen);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jblogin, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtpasswd, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtname, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jbclear, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(18, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtpasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblogin)
                    .addComponent(jbclear))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmbeendenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbeendenActionPerformed
        // Programm - beenden
        System.exit(0);
    }//GEN-LAST:event_jmbeendenActionPerformed

    private void jbclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbclearActionPerformed
        // Clear Button
        jtname.setText("");
        jtpasswd.setText("");
    }//GEN-LAST:event_jbclearActionPerformed

    private void jbloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbloginActionPerformed
      // Login Button
      //Das Logo wird nun animiert :D 
      jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo_animiert_144.gif")));
      //instanz der Klasse Einstellung holen
      Einstellungen E = new Einstellungen();
      //Benutzername holen 
      String name =  jtname.getText();
      //Passworteingabe auslesen
      char[] zeichen = jtpasswd.getPassword();
      //Eingabe in den MD5 Hashwert wandeln
      String passwort = E.build_md5(new String(zeichen));
      //variable für den Code Bilden (0=falsch / 1=benutzer||Passwort vorhanden)
      int code = 0;
      //Connection zum Server aufbauen
      TestService myServiceCaller = E.connection();
      //name und passwort an den Server senden und den Code abholen
      code = myServiceCaller.LoginMD5(name, passwort);
      System.out.print("Login Code: "+code+"\n");
      //ausgabe String anlegen
      String ausgabe = " ";
      //Prüfen
      if(code == 0) //wenn die eingabe falsch ist
      {
        ausgabe = "Benutzer / Kennwort falsch";
        JOptionPane.showMessageDialog(null, ausgabe, "Willkommen", JOptionPane.ERROR_MESSAGE);
        
        int ok = JOptionPane.showConfirmDialog(null, "Erneut versuchen", "Login", JOptionPane.YES_NO_OPTION);
        //Erneutes ausführen ?
        if(ok == 0) 
        {
          jtname.setText("");
          jtpasswd.setText("");
        }
        else
        { 
          System.exit(0);
        }
      }
      else if ((code >= 1)&&(code < 100)) //wenn der code über 1 liegt (es mindestens eine kombination gibt)  
      {
        //Benutzer id holen
        int id = myServiceCaller.get_idMD5(name, passwort);
        //Benutzerrecht holen
        int recht = myServiceCaller.get_rechtMD5(name, passwort);
        //ausgabe - Mesage für den Benutzer ausgeben
        ausgabe = "Eingabe korrekt!\n" + "Hallo " + name +" deine ist ID: " + id + "\nRecht: " + recht;        //ausgabe String basteln
        JOptionPane.showMessageDialog(null, ausgabe, "Willkommen", JOptionPane.INFORMATION_MESSAGE);  //ausgabe in einer Message Box
       //Connectionw wieder schliesen
        E.connection_close();
        //Verwaltung-Hauptfenster aufrufen und und login Fenster stumm schalten
        Verwaltung ver = new Verwaltung(id, recht, name);
        //loginFenster unsichtbar schalten
        this.setVisible(false);
        //Hauptfenster sichtbar schalten
        ver.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        ver.setVisible(true);
        //dieses Fenster zerstören um speicher freizugeben
        this.dispose();
      } // end of if-else
      
    }//GEN-LAST:event_jbloginActionPerformed

    private void jmeinstellungenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmeinstellungenActionPerformed
        // Einstellungen Menü aufrufen
        Einstellungen E = new Einstellungen();
       //Mesage Dislog für den Benutzer erzeugen
        JLabel l = new JLabel("Eingabe Master Passwort");
        JPasswordField jtpasswortfeld = new JPasswordField(10);
        JPanel JP = new JPanel();
        JP.setLayout((new GridLayout(2,1,10,20)));
        add(JP);
        JP.add(l);
        JP.add(jtpasswortfeld);
        JOptionPane.showMessageDialog(null,JP,"Passwort eingabe",JOptionPane.QUESTION_MESSAGE);
        //Eingabe abholen und in den MD5 wert wandeln
        char[] zeichen = jtpasswortfeld.getPassword();
        String ep = E.build_md5(new String(zeichen));
        //vergleichen ob die eingabe mit der master.dat übereinstimmt - siehe Enstellungen.java
        if (ep.equals(E.auslesen_masterpw()))
        {
            E.setVisible(true); 
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Eingabe ist nicht korrekt", "Fehler", JOptionPane.PLAIN_MESSAGE);
            E.dispose();
        }
        
    }//GEN-LAST:event_jmeinstellungenActionPerformed

    private void jmloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmloginActionPerformed
   // Login Button im Menüeintrag
      //Das Logo wird nun animiert :D 
      jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo_animiert_144.gif")));
      //instanz der Klasse Einstellung holen
      Einstellungen E = new Einstellungen();
      //Benutzername holen 
      String name =  jtname.getText();
      //Passworteingabe auslesen
      char[] zeichen = jtpasswd.getPassword();
      //Eingabe in den MD5 Hashwert wandeln
      String passwort = E.build_md5(new String(zeichen));
      //variable für den Code Bilden (0=falsch / 1=benutzer||Passwort vorhanden)
      int code = 0;
      //Connection zum Server aufbauen
      TestService myServiceCaller = E.connection();
      //name und passwort an den Server senden und den Code abholen
      code = myServiceCaller.LoginMD5(name, passwort);
      System.out.print("Login Code: "+code+"\n");
      //ausgabe String anlegen
      String ausgabe = " ";
      //Prüfen
      if(code == 0) //wenn die eingabe falsch ist
      {
        ausgabe = "Benutzer / Kennwort falsch";
        JOptionPane.showMessageDialog(null, ausgabe, "Willkommen", JOptionPane.ERROR_MESSAGE);
        
        int ok = JOptionPane.showConfirmDialog(null, "Erneut versuchen", "Login", JOptionPane.YES_NO_OPTION);
        //Erneutes ausführen ?
        if(ok == 0) 
        {
          jtname.setText("");
          jtpasswd.setText("");
        }
        else
        { 
          System.exit(0);
        }
      }
      else if ((code >= 1)&&(code < 100)) //wenn der code über 1 liegt (es mindestens eine kombination gibt)  
      {
        //Benutzer id holen
        int id = myServiceCaller.get_idMD5(name, passwort);
        //Benutzerrecht holen
        int recht = myServiceCaller.get_rechtMD5(name, passwort);
        //ausgabe - Mesage für den Benutzer ausgeben
        ausgabe = "Eingabe korrekt!\n" + "Hallo " + name +" deine ist ID: " + id + "\nRecht: " + recht;        //ausgabe String basteln
        JOptionPane.showMessageDialog(null, ausgabe, "Willkommen", JOptionPane.INFORMATION_MESSAGE);  //ausgabe in einer Message Box
       //Connectionw wieder schliesen
        E.connection_close();
        //Verwaltung-Hauptfenster aufrufen und und login Fenster stumm schalten
        Verwaltung ver = new Verwaltung(id, recht, name);
        //loginFenster unsichtbar schalten
        this.setVisible(false);
        //Hauptfenster sichtbar schalten
        ver.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        ver.setVisible(true);
        //dieses Fenster zerstören um speicher freizugeben
        this.dispose();
      } // end of if-else
    }//GEN-LAST:event_jmloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbclear;
    private javax.swing.JButton jblogin;
    private javax.swing.JMenu jbprogramm;
    private javax.swing.JMenuItem jmbeenden;
    private javax.swing.JMenuItem jmeinstellungen;
    private javax.swing.JMenuItem jmlogin;
    private javax.swing.JMenu jmoptionen;
    private javax.swing.JTextField jtname;
    private javax.swing.JPasswordField jtpasswd;
    // End of variables declaration//GEN-END:variables

}
