/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package verwaltung;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import lipermi.handler.CallHandler;
import lipermi.handler.filter.GZipFilter;
import lipermi.net.Client;
import testcommon.TestService;

/**
 *
 * @author Limbo
 */
public class Verwaltung extends javax.swing.JFrame {

    //Klassenweite variablen
    int id, recht, akt = 0;
    String name, kdnr, vorname, nachname, status;
    TestService myServiceCaller = null;
    Client client;
    String [][] alle;

    //Konstruktor
    public Verwaltung(int id, int recht, String name) 
    {
    //Fenster Image einblenden
    Image icon = new ImageIcon("ic_lagerverwaltung32.gif").getImage();
    setIconImage(icon);
    
    //Alle Komponenten laden
    initComponents();

    //Übergebene Werte aus dem Konsturktor abholen
    this.id=id;
    this.recht=recht;
    this.name=name;
    //Verbindung aufbauen zum Server und speichern
    Einstellungen E = new Einstellungen();
    myServiceCaller = E.connection();
    jlbenutzer.setText(jlbenutzer.getText() + name + " mit der id: "+id+", Recht: "+recht);
    
    //durch das setzen des status wird die suche schon ausgeführt - create table damit nicht mehr notwendig
    jcstatus.setSelectedIndex(1);
    //Abfragen der Benutzerrechte - damit verbunden das Anzeigen der Elemente
    if (recht == 3)
    {
        jbnb.setVisible(false);
        jmbenutzerverwaltung.setForeground(Color.GRAY);
        jmeinstellungen.setForeground(Color.GRAY);
        jmuebersicht.setForeground(Color.GRAY);
    }
    
    //Statustask wird gestartet (siehe Status.java)
    Status s = new Status("Statusfeld",jlstatusserver,jluhrzeit,jlstatusDatenbank,myServiceCaller,this);
    s.start();
    }

    //Erstellung der Tabelle - Tabelle fuellen
    //auflistung aller aktueller bestellungen
    void createTable(int auswahl) 
    { 
        //Holen aller Datensätze
        alle = myServiceCaller.aktBestellungen(auswahl);

        //Tabelle füllen
        Object[] row = new Object[10];
        DefaultTableModel model = (DefaultTableModel) jtauftragakt.getModel();
        
        for (int i=0; i< alle.length; i++)
        {
            row[0]= alle[i][0];
            row[1]= alle[i][1];
            row[2]= alle[i][2];
            row[3]= alle[i][3];
            row[4]= alle[i][4];
            row[5]= alle[i][5];
            row[6]= alle[i][6];

            model.addRow(row);
        }
        
        //Anzahl der Zeilen anzeigen
        jlrows.setText(alle.length + " Rows returned");
    }
    
    //Methode, wenn eine suche ausgeführt wird das die Tabelle mit den Daten 
    //gefüllt wird
    void fuellemitsuche() //ähnlich wie bei createtable()
    {
    if (alle.length > 0)
        {
            //Tabelle füllen
            Object[] row = new Object[10];
            DefaultTableModel model = (DefaultTableModel) jtauftragakt.getModel();
            model.setRowCount(0);

            for (int i=0; i< alle.length; i++)
            {
                row[0]= alle[i][0];
                row[1]= alle[i][1];
                row[2]= alle[i][2];
                row[3]= alle[i][3];
                row[4]= alle[i][4];
                row[5]= alle[i][5];
                row[6]= alle[i][6];

                model.addRow(row);
            }

            //Anzahl der Zeilen anzeigen
            jlrows.setText(alle.length + " Rows returned");
        }
    else //wenn nichts gefunden wird
        {
               JOptionPane.showMessageDialog(null, "Ihre Suche hat nichts ergeben!", "Fehler", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jbkundenstamm = new javax.swing.JButton();
        jlbenutzer = new javax.swing.JLabel();
        jbartikelstamm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtauftragakt = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtsuche = new javax.swing.JTextField();
        jbsuchen = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtausg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtbestellnr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbrefresh = new javax.swing.JButton();
        jbopen = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jcstatus = new javax.swing.JComboBox<>();
        jbnb = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jdcvon = new com.toedter.calendar.JDateChooser();
        jdcbis = new com.toedter.calendar.JDateChooser();
        jbclear = new javax.swing.JButton();
        jlrows = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlstatusserver = new javax.swing.JLabel();
        jluhrzeit = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlstatusDatenbank = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jmuebersicht = new javax.swing.JMenuItem();
        jmabmelden = new javax.swing.JMenuItem();
        jmbeenden = new javax.swing.JMenuItem();
        optionen = new javax.swing.JMenu();
        jmeinstellungen = new javax.swing.JMenuItem();
        jmean = new javax.swing.JMenuItem();
        jmbenutzerverwaltung = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Verwaltung");
        setLocation(new java.awt.Point(200, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Verwaltung - Hauptfenster");

        jbkundenstamm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/kunden.gif"))); // NOI18N
        jbkundenstamm.setText("Kundenstamm");
        jbkundenstamm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbkundenstammActionPerformed(evt);
            }
        });

        jlbenutzer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbenutzer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.gif"))); // NOI18N
        jlbenutzer.setText("Willkommen Benutzer: ");

        jbartikelstamm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/article.gif"))); // NOI18N
        jbartikelstamm.setText("Artikelstamm");
        jbartikelstamm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbartikelstammActionPerformed(evt);
            }
        });

        jtauftragakt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Zeit", "Bestell_ID", "Status", "Kunden_Nr", "Nachname", "Vorname", "Summe Artikel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtauftragakt.setToolTipText("Doppelklick öffnet");
        jtauftragakt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtauftragaktMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtauftragakt);
        if (jtauftragakt.getColumnModel().getColumnCount() > 0) {
            jtauftragakt.getColumnModel().getColumn(0).setPreferredWidth(120);
            jtauftragakt.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Ausgewählt");

        jbsuchen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.gif"))); // NOI18N
        jbsuchen.setText("Bestellung suchen");
        jbsuchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsuchenActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("aktuelle Bestellungen");

        jLabel4.setText("Bestell_Nr:");

        jLabel5.setText("Details:");

        jbrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.gif"))); // NOI18N
        jbrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrefreshActionPerformed(evt);
            }
        });

        jbopen.setText("Bestellung öffnen");
        jbopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbopenActionPerformed(evt);
            }
        });

        jLabel6.setText("Anzeigen:");

        jcstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alle", "in Bearbeitung", "Abgeschlossen", "Cancel" }));
        jcstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcstatusActionPerformed(evt);
            }
        });

        jbnb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.gif"))); // NOI18N
        jbnb.setText("Neue Bestellung");
        jbnb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnbActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Bestellung suchen");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("von");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("bis");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Bestell_ID");

        jbclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clear.gif"))); // NOI18N
        jbclear.setText("clear");
        jbclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(279, 279, 279)
                        .addComponent(jbnb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtbestellnr, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbrefresh)
                                .addComponent(jbopen))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtausg, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jdcvon, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jdcbis, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtsuche)
                            .addComponent(jbsuchen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(132, 132, 132)
                                        .addComponent(jLabel10)))
                                .addGap(50, 50, 50)))
                        .addGap(18, 18, 18)
                        .addComponent(jbclear)))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbrefresh)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbnb)
                            .addComponent(jLabel8)))
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jbopen))
                            .addComponent(jdcbis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtbestellnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jdcvon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtausg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtsuche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbsuchen)
                    .addComponent(jbclear))
                .addContainerGap())
        );

        jlrows.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table.gif"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_lagerverwaltung144.gif"))); // NOI18N

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlstatusserver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/online.gif"))); // NOI18N
        jlstatusserver.setText("jLabel11");

        jluhrzeit.setText("jLabel11");

        jLabel11.setText("letzte akt. :");
        jLabel11.setToolTipText("letzte akualisierung");

        jlstatusDatenbank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/online.gif"))); // NOI18N
        jlstatusDatenbank.setText("jLabel13");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlstatusserver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jluhrzeit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jlstatusDatenbank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlstatusserver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlstatusDatenbank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jluhrzeit))
                .addContainerGap())
        );

        jMenu1.setText("Verwaltung");

        jMenu4.setText("Bestellungen");

        jmuebersicht.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jmuebersicht.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/printer.gif"))); // NOI18N
        jmuebersicht.setText("Übersicht drucken");
        jmuebersicht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmuebersichtActionPerformed(evt);
            }
        });
        jMenu4.add(jmuebersicht);

        jMenu1.add(jMenu4);

        jmabmelden.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jmabmelden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.gif"))); // NOI18N
        jmabmelden.setText("Abmelden");
        jmabmelden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmabmeldenActionPerformed(evt);
            }
        });
        jMenu1.add(jmabmelden);

        jmbeenden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ausschalten.gif"))); // NOI18N
        jmbeenden.setText("Beenden");
        jmbeenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbeendenActionPerformed(evt);
            }
        });
        jMenu1.add(jmbeenden);

        jMenuBar1.add(jMenu1);

        optionen.setText("optionen");

        jmeinstellungen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmeinstellungen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/settings.gif"))); // NOI18N
        jmeinstellungen.setText("Einstellungen");
        jmeinstellungen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmeinstellungenActionPerformed(evt);
            }
        });
        optionen.add(jmeinstellungen);

        jmean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/barcode.gif"))); // NOI18N
        jmean.setText("EANconfig");
        jmean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmeanActionPerformed(evt);
            }
        });
        optionen.add(jmean);

        jmbenutzerverwaltung.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jmbenutzerverwaltung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/kunden.gif"))); // NOI18N
        jmbenutzerverwaltung.setText("Benutzerverwaltung");
        jmbenutzerverwaltung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbenutzerverwaltungActionPerformed(evt);
            }
        });
        optionen.add(jmbenutzerverwaltung);

        jMenuBar1.add(optionen);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlrows, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(600, 600, 600))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbenutzer, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbkundenstamm, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbartikelstamm, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbenutzer)
                            .addComponent(jbkundenstamm)
                            .addComponent(jbartikelstamm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlrows)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmbeendenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbeendenActionPerformed
        // wenn der beenden Menüpunkt gedrückt wird
        System.exit(0); 
    }//GEN-LAST:event_jmbeendenActionPerformed

    private void jbkundenstammActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbkundenstammActionPerformed
        // Kundenstamm aufrufen
      Kundenstamm kundenstamm = new Kundenstamm(name, recht);
      kundenstamm.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
      kundenstamm.setVisible(true);
    }//GEN-LAST:event_jbkundenstammActionPerformed

    private void jmabmeldenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmabmeldenActionPerformed
        // abmelden
        this.setVisible(false);     //aktuelles Fenster wird unsichtbargemacht
        Login log = new Login();    //das Login Fesnter erzeugt
        log.setVisible(true);       // und sichtbar geschaltet
        this.dispose();             //Verwaltungsfenster wird geschlossen
    }//GEN-LAST:event_jmabmeldenActionPerformed

    private void jmeinstellungenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmeinstellungenActionPerformed
        // Öffnen des Einstellungen Fenster
        if (recht == 1)
        {
        //erzeugung des Fenster-Objekt Einstellungen
        Einstellungen E = new Einstellungen();
        
        //Message Dialog wird erstellt
        JLabel l = new JLabel("Eingabe Master Passwort");
        JPasswordField jtpasswortfeld = new JPasswordField(10);
        JPanel JP = new JPanel();
        JP.setLayout((new GridLayout(2,1,10,20)));
        add(JP);
        JP.add(l);
        JP.add(jtpasswortfeld);
        JOptionPane.showMessageDialog(null,JP,"Passwort eingabe",JOptionPane.QUESTION_MESSAGE);

        //eingabe wird Passwort in der master.dat verglichen (siehe Einstellungen.java)
        char[] zeichen = jtpasswortfeld.getPassword();
        String ep = E.build_md5(new String(zeichen));
            //wenn die eingabe richtig ist geht es weiter
            if (ep.equals(E.auslesen_masterpw()))
            {
                E.setVisible(true); 
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Eingabe ist nicht korrekt", "Fehler", JOptionPane.ERROR_MESSAGE);
                E.dispose();
            }
        }

  
    }//GEN-LAST:event_jmeinstellungenActionPerformed

    private void jbartikelstammActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbartikelstammActionPerformed
        // Artikelstamm öffnen
        Artikelstamm AS = new Artikelstamm(name, recht);
        AS.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        AS.setVisible(true);
    }//GEN-LAST:event_jbartikelstammActionPerformed

    private void jmeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmeanActionPerformed
        // EAN Config starten
        EANconfig EAN = new EANconfig();
        EAN.setVisible(true);
    }//GEN-LAST:event_jmeanActionPerformed

    private void jtauftragaktMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtauftragaktMouseClicked
        // Klichen auf die Tabellen Spalte
        //angeklickte Zeile auslesen und abspeichern in klassenwiter variable
        int i = jtauftragakt.getSelectedRow();
        akt = i;
        //die angeklickte Zeile Blau hinterlegen
        jtauftragakt.setSelectionBackground(Color.blue);
        //Tabelle Modell holen
        TableModel model = jtauftragakt.getModel();
        //status herausziehen
        status = ((String) model.getValueAt(i, 2));
        //Textfelder / Combofelder bestücken
        jtbestellnr.setText((String) model.getValueAt(i, 1));
        kdnr = ((String) model.getValueAt(i, 3));
        nachname = ((String) model.getValueAt(i, 4));
        vorname = ((String) model.getValueAt(i, 5));
        String sum = ((String) model.getValueAt(i, 6));
        
        jtausg.setText("Kunde: "+kdnr+", "+nachname+", "+vorname+", "+sum+" Artikel" );
        //bei einem Doppelklick wird die Bestellung direkt geöffnet
        if (evt.getClickCount()==2) 
        { 
            if (jtbestellnr.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Bitte eine Bestellung wählen!", "Fehler", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                Bestellung B = new Bestellung(recht, name, jtbestellnr.getText(),kdnr, vorname, nachname, status);
                B.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
                B.setVisible(true);
            }         
	}
    }//GEN-LAST:event_jtauftragaktMouseClicked

    private void jbnbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnbActionPerformed
        // Bestellungsfenster öffnen
        Bestellung b = new Bestellung(id, recht, name);
        b.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        b.setVisible(true);
    }//GEN-LAST:event_jbnbActionPerformed

    private void jcstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcstatusActionPerformed
        // Auswahl des JComboField
        DefaultTableModel model = (DefaultTableModel) jtauftragakt.getModel();
        model.setRowCount(0);
        createTable(jcstatus.getSelectedIndex());
    }//GEN-LAST:event_jcstatusActionPerformed

    private void jbopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbopenActionPerformed
        // bestehende Bestellung öffnen
        if (jtbestellnr.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Bitte eine Bestellung wählen!", "Fehler", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            Bestellung B = new Bestellung(recht, name, jtbestellnr.getText(),kdnr, vorname, nachname, status);
            B.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
            B.setVisible(true);
        }
    }//GEN-LAST:event_jbopenActionPerformed

    private void jbrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrefreshActionPerformed
        // Refresh der Bestellungen
        DefaultTableModel model = (DefaultTableModel) jtauftragakt.getModel();
        model.setRowCount(0);
        createTable(1); //beim refresh kommen die Bestellungen der die in bearbeitung sind
    }//GEN-LAST:event_jbrefreshActionPerformed

    private void jbsuchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsuchenActionPerformed
        // suchen
        //anlegen von Variablen
        String Datevon="", Datebis="", Suchbegriff="";
         //Simple date für die Formatierung wählen
         SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
         Date d = new Date();
        //überprüfen ob der kalender gesetzt ist (!=null)
        if ((jdcvon.getCalendar() != null)&&(jdcbis.getCalendar() != null))
        {
            //wandlung der Millisekunden in Zeitformate 
            //(Datebis wird noch um einen Tag hochgezählt) 
            //-> bei gleichem Datum wäre kein beetween im SQL Befehl mehr möglich
            Datevon = s.format(jdcvon.getCalendar().getTimeInMillis());
            Datebis = s.format(jdcbis.getCalendar().getTimeInMillis()+10000000);
            System.out.println(Datebis);
            //Suchbegriff abspeichern
            Suchbegriff = jtsuche.getText();
            //Suche ausführen und Daten holen
            alle = myServiceCaller.sucheBestellung(Datevon, Datebis, Suchbegriff);
            //Methode ausführen
            fuellemitsuche();
        }//Falls kein Datum ausgeählt wurd (==null)
        else if ((jdcvon.getCalendar() == null)&&(jdcbis.getCalendar() == null))
        {
            //bei keiner auswahl zur suche den gesamten Programmzeitraum angeben
            Datevon = "2016-01-01";
            Datebis = s.format(d);
            //Suchbegriff abspeichern
            Suchbegriff = jtsuche.getText();
            //Suche ausführen und Daten holen
            alle = myServiceCaller.sucheBestellung(Datevon, Datebis, Suchbegriff);  
            //fuellen methode ausführen
            fuellemitsuche();
        }    
        else
        {
            JOptionPane.showMessageDialog(null, "Bitte einen Zeitraum angeben!", "Fehler", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbsuchenActionPerformed

    private void jbclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbclearActionPerformed
        // clear button
        jdcvon.setDate(null);
        jdcbis.setDate(null);
        jtsuche.setText("");
        jcstatus.setSelectedIndex(1);
    }//GEN-LAST:event_jbclearActionPerformed

    private void jmuebersichtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmuebersichtActionPerformed
        // Bestelluebersicht drucken
        // nur als Administrator oder Anwender möglich
        if ((recht == 1)||(recht == 2))
        {
        Print p = new Print("Print");
        p.druckeBestellung(alle);
        }
    }//GEN-LAST:event_jmuebersichtActionPerformed

    private void jmbenutzerverwaltungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbenutzerverwaltungActionPerformed
        // Benutzerverwaltung
        //nur mit Administrator rechten möglich
        if (recht==1)
        {
            Benutzerverwaltung Be = new Benutzerverwaltung();
            Be.setVisible(true);
        }
    }//GEN-LAST:event_jmbenutzerverwaltungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verwaltung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verwaltung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verwaltung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verwaltung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new Verwaltung(00,1,"Test-Umgebung").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbartikelstamm;
    private javax.swing.JButton jbclear;
    private javax.swing.JButton jbkundenstamm;
    private javax.swing.JButton jbnb;
    private javax.swing.JButton jbopen;
    private javax.swing.JButton jbrefresh;
    private javax.swing.JButton jbsuchen;
    private javax.swing.JComboBox<String> jcstatus;
    private com.toedter.calendar.JDateChooser jdcbis;
    private com.toedter.calendar.JDateChooser jdcvon;
    private javax.swing.JLabel jlbenutzer;
    private javax.swing.JLabel jlrows;
    private javax.swing.JLabel jlstatusDatenbank;
    private javax.swing.JLabel jlstatusserver;
    private javax.swing.JLabel jluhrzeit;
    private javax.swing.JMenuItem jmabmelden;
    private javax.swing.JMenuItem jmbeenden;
    private javax.swing.JMenuItem jmbenutzerverwaltung;
    private javax.swing.JMenuItem jmean;
    private javax.swing.JMenuItem jmeinstellungen;
    private javax.swing.JMenuItem jmuebersicht;
    private javax.swing.JTable jtauftragakt;
    private javax.swing.JTextField jtausg;
    private javax.swing.JTextField jtbestellnr;
    private javax.swing.JTextField jtsuche;
    private javax.swing.JMenu optionen;
    // End of variables declaration//GEN-END:variables
}
